sudo: false

git:
  depth: 1

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
    sources:
      - trusty
    packages:
      - libboost-system-dev
      - libboost-wave-dev
      - tcl
      - qdbus
      - qmlscene
      - qt5-default
      - qt5-qmake
      - qtbase5-dev-tools
      - qtchooser
      - qtdeclarative5-dev
      - xbitmaps
      - xterm
      - libqt5svg5-dev
      - qttools5-dev
      - qtscript5-dev
      - xvfb

env:
  - CONFIG=debug     VERA=false    SUFFIX=-d
  - CONFIG=release   VERA=false   SUFFIX=

before_install:
  - pip install --user codecov

install:
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - Xvfb :0 &
  - export DISPLAY=:0

script:
  - $(CXX) --version
  - qmake --version
  - if [ "$VERA" = "true" ]; then tclsh vera++/generatePaths.tcl; fi
  - if [ "$VERA" = "true" ]; then vera++ --error -p allRules --root vera++ <vera++/params; fi
  - qmake trikRuntime.pro CONFIG+=$CONFIG
  - make -j2
  - cd tests
  - qmake -r CONFIG+=$CONFIG tests.pro
  - make -j2
  - cd minimalCppApp
  - qmake -r CONFIG+=$CONFIG minimalCppApp.pro
  - make -j2
  - cd ../../bin/x86-$CONFIG
  - ls -A
  - sh -c "./trikScriptRunnerTests-x86$SUFFIX"
  - sh -c "./trikCommunicatorTests-x86$SUFFIX"
  - sh -c "./trikKernelTests-x86$SUFFIX"
  - cd ../..

after_success:
  - if [ "$CONFIG" = "debug" ]; then codecov; fi
